version: "2"

services:
  app:
    build: .
    ports:
    - "8080:8080"
    environment:
       MONGOHOST: db
       MONGOUSERNAME: "root"
       MONGOPASSWORD: "example"
       TEAMNAME: "test"
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example